import { createFileRoute } from "@tanstack/react-router";
import { db } from "../../../db/index.js";
import { rooms } from "../../../db/schema.js";

const sampleRooms = [
  {
    title: "Furnished 1BHK Near Collectorate",
    description: "Spacious 1BHK flat with all modern amenities. Located in a prime area near Collectorate. Ideal for working professionals and small families.",
    area: "Civil Lines",
    locality: "Collectorate Road",
    address: "Near HDFC Bank, Civil Lines, Sultanpur",
    pricePerMonth: 7500,
    bedrooms: 1,
    bathrooms: 1,
    furnishing: "furnished",
    roomType: "private",
    amenities: "WiFi,AC,Geyser,Parking",
    contactName: "Ramesh Sharma",
    contactPhone: "9876543210",
    available: true,
    imageUrl: "",
  },
  {
    title: "Single Room for Bachelors – Chowk Area",
    description: "Clean single room available for bachelors. Close to market and bus stand. Water and electricity extra.",
    area: "Chowk",
    locality: "Chowk Bazar",
    address: "Near Axis Bank, Chowk, Sultanpur",
    pricePerMonth: 3000,
    bedrooms: 1,
    bathrooms: 1,
    furnishing: "unfurnished",
    roomType: "shared",
    amenities: "Water,Electricity",
    contactName: "Sunil Verma",
    contactPhone: "9812345678",
    available: true,
    imageUrl: "",
  },
  {
    title: "2BHK Semi-Furnished Flat – Amethi Road",
    description: "Well-maintained 2BHK flat on first floor. Near school and hospital. Families preferred.",
    area: "Amethi Road",
    locality: "Lalbagh Colony",
    address: "Lalbagh Colony, Amethi Road, Sultanpur",
    pricePerMonth: 10000,
    bedrooms: 2,
    bathrooms: 2,
    furnishing: "semi-furnished",
    roomType: "private",
    amenities: "Geyser,Fan,Parking,Garden",
    contactName: "Priya Singh",
    contactPhone: "9988776655",
    available: true,
    imageUrl: "",
  },
  {
    title: "PG Accommodation for Girls – Dubeypur",
    description: "Safe PG accommodation for girls near Saket Degree College. Meals available. Strict timing for security.",
    area: "Dubeypur",
    locality: "College Road",
    address: "Near Saket Degree College, Dubeypur, Sultanpur",
    pricePerMonth: 5000,
    bedrooms: 1,
    bathrooms: 1,
    furnishing: "furnished",
    roomType: "pg",
    amenities: "WiFi,Meals,Laundry,CCTV",
    contactName: "Anita Devi",
    contactPhone: "9911223344",
    available: true,
    imageUrl: "",
  },
  {
    title: "Spacious Room – Alambagh Colony",
    description: "Large room with attached bathroom on ground floor. Suitable for students or couples. Kitchen access available.",
    area: "Alambagh",
    locality: "Alambagh Colony",
    address: "Alambagh Colony, Near Water Tank, Sultanpur",
    pricePerMonth: 4500,
    bedrooms: 1,
    bathrooms: 1,
    furnishing: "semi-furnished",
    roomType: "private",
    amenities: "Fan,Water,Kitchen",
    contactName: "Mohan Lal",
    contactPhone: "9000112233",
    available: true,
    imageUrl: "",
  },
  {
    title: "3BHK Independent House – Nawabganj",
    description: "Full independent house with terrace, perfect for large families. Good connectivity to city centre.",
    area: "Nawabganj",
    locality: "Nawabganj Main Road",
    address: "Main Road, Nawabganj, Sultanpur",
    pricePerMonth: 18000,
    bedrooms: 3,
    bathrooms: 2,
    furnishing: "unfurnished",
    roomType: "private",
    amenities: "Terrace,Parking,Water,Electricity",
    contactName: "Arvind Pandey",
    contactPhone: "9775544332",
    available: true,
    imageUrl: "",
  },
  {
    title: "Budget Room Near Railway Station",
    description: "Affordable room very close to Sultanpur Railway Station. Ideal for daily commuters and travelers.",
    area: "Railway Colony",
    locality: "Station Road",
    address: "Station Road, Railway Colony, Sultanpur",
    pricePerMonth: 2500,
    bedrooms: 1,
    bathrooms: 1,
    furnishing: "unfurnished",
    roomType: "shared",
    amenities: "Water,Electricity",
    contactName: "Dinesh Kumar",
    contactPhone: "9654321098",
    available: true,
    imageUrl: "",
  },
  {
    title: "AC Room in Modern Flat – Lambua Road",
    description: "Fully air-conditioned room in a modern flat complex. 24-hour security and backup power.",
    area: "Lambua Road",
    locality: "New Colony",
    address: "New Colony, Lambua Road, Sultanpur",
    pricePerMonth: 9000,
    bedrooms: 1,
    bathrooms: 1,
    furnishing: "furnished",
    roomType: "private",
    amenities: "AC,WiFi,Power Backup,Security",
    contactName: "Kavita Mishra",
    contactPhone: "9871234560",
    available: true,
    imageUrl: "",
  },
];

export const Route = createFileRoute("/api/seed")({
  server: {
    handlers: {
      POST: async () => {
        await db.insert(rooms).values(sampleRooms);
        return Response.json({ message: "Seeded successfully", count: sampleRooms.length });
      },
    },
  },
});
